version: "3.7"

services:
  app-node:

    build: ./appNodejs
    container_name: "app-nodejs"
    working_dir: "/home/node/app"
    expose:
      - "8055"
    ports:
      - "8055:8000"
    command: "node index.js"
  
  app-python:
    build: ./appPython
    container_name: "app-python"
    working_dir: "/app"
    expose:
      - "8056"
    ports:
      - "8056:8000"
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"

  app-web:
    build: ./appWeb
    container_name: "app-web-nginx"
    expose:
    - "8087"
    ports:
      - "8057:80"
    command: ["nginx", "-g", "daemon off;"]
  
  app-php:
    build: ./appPhp
    container_name: app-php
    ports:
      - "8058:80"
  
  mysql:
    image: mysql:latest
    container_name: "mysql"
    volumes:
      - dados-do-banco:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: unifafibe
    ports:
      - "3306:3306"

volumes:
  dados-do-banco:
    external: true