version: "3.7"

services:
  app-node:

    build: ./appNodejs
    container_name: "app-nodejs"
    working_dir: "/home/node/app"
    expose:
      - "8055"
    ports:
      - "8055:8000"
    command: "node index.js"
  
  app-python:
    build: ./appPython
    container_name: "app-python"
    working_dir: "/app"
    expose:
      - "8056"
    ports:
      - "8056:8000"
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"
    